OpenSCAP/oval-graph

graph/oval_graph.py, html_interpreter/index.html, tests/test_graph.py, tests/test_sigmaJs.py
Adds a negation visualization.
=> Negation graph

graph/oval_graph.py, graph/xml_parser.py, tests/any_test_help.py, tests/test_graph.py, tests/test_sigmaJs.py
=> Recognition of notselected rules

graph/oval_graph.py, tests/test_graph.py
In XML result of negated test is automatically negated.
=> Fix evaluation negated tests and CI Tests

graph/oval_graph.py, graph/xml_parser.py, tests/test_data/rule_dict.json
Append XML_parser ability parse comments form oval-definition.
This is first PR of appending of comments form oval-definition to graphs.
=> XML_parser ability parse comments form oval-definition

graph/xml_parser.py, tests/data_cleaner.py, tests/test_data/JsTree_json0.json, tests/test_data/JsTree_json1.json, tests/test_data/referenc_result_data_graph.js, tests/test_data/rule_dict.json, tests/test_data/sigmaJs_json0.json, tests/test_data/sigmaJs_json1.json
This PR fixed problem with displaying comments in extended definitions.
=> Fixed bug - displaying comments in extended definitions

graph/xml_parser.py, tests/test_data/JsTree_json0.json, tests/test_data/JsTree_json1.json, tests/test_data/referenc_result_data_graph.js, tests/test_data/referenc_result_data_tree.js, tests/test_data/rule_dict.json, tests/test_data/sigmaJs_json0.json, tests/test_data/sigmaJs_json1.json
This PR append title of oval definition to top node.
=> Title of oval definition in top node

graph/client.py, graph/xml_parser.py
=> Fixed running run.py from outside of the projects directory

oval_graph/xml_parser.py, tests/any_test_help.py, tests/test_xml_parser.py
This PR remove `py` library, because usage in packages is problematic.
=> Removed py library usage

oval_graph/command_line.py, oval_graph/oval_graph.py
This PR include:
- fix typing error
- update docstring
=> Fix typing error

oval_graph/client.py, oval_graph/command_line.py, oval_graph/xml_parser.py, tests/test_client.py
This PR changes the output of the graph to the directory in /tmp.
Fixes: #38
=> Output of html

oval_graph/client.py, oval_graph/command_line.py, oval_graph/converter.py, oval_graph/oval_node.py, oval_graph/xml_parser.py, tests/any_test_help.py, tests/test_JsTree.py, tests/test_client.py, tests/test_evaluate.py, tests/test_graph.py, tests/test_xml_parser.py
This PR changes:
- Imports in project 
- Class name ovalNode to oval_node
- File name oval_graph.py to oval_node.py
=> Change imports

MANIFEST.in, README.md, setup.py
These PRs include:
- deleted forgotten include
- changed wording client to tool
=> Prepare on build

oval_graph/client.py, tests/any_test_help.py, tests/test_client.py
This PR include:
-  a new `--out` option that allows you to choose where to save output files 
- rework test
Fixes: #53
=> Save the output files to the selected directory 

oval_graph/arf_to_html.py, oval_graph/client.py, oval_graph/command_line.py, tests/any_test_help.py, tests/test_arf_to_hml.py, tests/test_client.py
This PR include rework of class Client and prepare code for new command `arf-to-json`.
=> Rework CLI Client

.gitignore, oval_graph/arf_to_html.py, oval_graph/client.py, oval_graph/command_line.py, oval_graph/json_to_html.py, setup.py, tests/conftest.py, tests/data_cleaner.py, tests/test_arf_to_hml.py, tests/test_arf_to_json.py, tests/test_json_to_html.py
This PR include:
- new command `json-to-graph` which transform rule form json to graph.
- change default output directory to Working directory
- change option `--out` to `--ouptut`
Fixes: #39
=> Add command json-to-graph

oval_graph/arf_to_json.py, oval_graph/client.py, tests/test_client.py
This PR contain:
- fix of bug #62 
- Added quotation mark to rules names in selection without installed inquirer for easter copy and paste 
Fixes: #62
=> Fixed redirecting output of command to file

.gitignore, benchmark.py, oval_graph/client.py, oval_graph/xml_parser.py
This PR include:
- Performance improvements in xml processing
Fixes: #68
=> Performance improvement

oval_graph/arf_to_html.py, oval_graph/arf_to_json.py, oval_graph/client.py, oval_graph/command_line.py, oval_graph/json_to_html.py, tests/test_client.py, tests/test_json_to_html.py
This PR include option ```--all``` witch process all matched rules.
=> New option for process all matched rules

build.sh
=> Changed status code to 1

build.sh
=> Fixed problem with exit code

build.sh
=> Fixed version change

build.sh
=> Fixed version check

build.sh
=> Fixed comparison of versions

build.sh
=> Fixed change version

build.sh
=> Fixed `if` in build.sh

.packit.yaml, oval-graph.spec
This PR contains packit config.
=> Packit config

oval_graph/xml_parser.py
=> Enable not valid arf files

oval_graph/oval_node.py
This PR fixed bug in transfer json to graph. Comment and tag was substitute.
=> Fix bug in transfer json to graph

oval_graph/converter.py, tests/test_JsTree_data/JsTree_data_0.json, tests/test_JsTree_data/JsTree_data_1.json, tests/test_JsTree_data/JsTree_data_2.json, tests/test_JsTree_data/JsTree_data_3.json, tests/test_JsTree_data/JsTree_data_4.json, tests/test_JsTree_data/JsTree_data_5.json, tests/test_JsTree_data/JsTree_data_negated_0.json, tests/test_JsTree_data/JsTree_data_negated_1.json, tests/test_JsTree_data/JsTree_data_negated_2.json, tests/test_JsTree_data/JsTree_data_negated_3.json, tests/test_data/JsTree_json0.json, tests/test_data/JsTree_json1.json
- fixes problem with negation not bool values error, noteval, etc.
- new label with result of node for better distinction nodes with values error, noteval, etc.
Fixes #85
=>  Fix problem with negation not bool values error, noteval, etc.

build.sh
=> Auto update spec file

MANIFEST.in
This PR fixes missing include html parts of report for package.
=> Fixes miss include for html parts of report

oval_graph/_builder_oval_graph.py, oval_graph/_xml_parser_comments.py, oval_graph/_xml_parser_oval_scan_definitions.py, oval_graph/_xml_parser_test_info.py, oval_graph/xml_parser.py, tests/test_xml_parser.py
This PR divides the `XmlParser` class by task into` _XmlParserComments`, `_XmlParserTestInfo`,` _XmlParserScanDefinitions`, `_BuilderOvalGraph`.
- `XmlParser` will process the xml file.
1 - `_XmlParserTestInfo` creates information about each test from the processed file. Test information is assigned to the rule definition when the rule definition is created by ID._
2 - `_XmlParserScanDefinitions` creates a dictionary of all rule definitions.
3 - `_XmlParserComments` creates a dictionary with comments from the processed file and inserts comments into the definition dictionary. _Comment comment has the same layout as the definition dictionary._
4 - `_BuilderOvalGraph` builds a rule graph from the rule definition dictionary.
=> Rework xml parser - split xml parser into smaller parts

MANIFEST.in
This PR fixes include to build necessary files for run application.
=> Fix build include

oval_graph/arf_to_html.py, oval_graph/arf_to_json.py, oval_graph/client.py, tests/any_test_help.py, tests/test_arf_to_hml.py, tests/test_arf_to_json.py
This PR fixes typo in parameter of command.
Fixes #96
=> Fix typo in parameter of command.

benchmark.py, oval_graph/_builder_oval_graph.py, oval_graph/_xml_parser_comments.py, oval_graph/_xml_parser_oval_scan_definitions.py, oval_graph/client.py, oval_graph/command_line.py, oval_graph/json_to_html.py, oval_graph/xml_parser.py, tests/test_client.py, tests/test_json_to_html.py, tests/test_xml_parser.py
This PR changes:
- internal arrays to dictionaries for sreaching performance improvement
- loading negation for nodes
=> Rework xml parser scan definitions

oval_graph/_builder_oval_graph.py, oval_graph/xml_parser.py
This PR reworks class ```_BuilderOvalGraph```.
=> Rework builder of oval graph

oval_graph/_xml_parser_comments.py
This PR reworks class ```_XmlParserComments```.
=> Rework xml parser for comments

oval_graph/arf_to_html.py, oval_graph/arf_to_json.py, oval_graph/client.py, oval_graph/command_line.py, oval_graph/converter.py, oval_graph/json_to_html.py, oval_graph/oval_node.py, oval_graph/xml_parser.py, tests/test_arf_to_hml.py, tests/test_arf_to_json.py, tests/test_client.py, tests/test_graph.py, tests/test_json_to_html.py, tests/test_xml_parser.py
This PR improves error message and error traceback for user.
Fixes #106
=> Improve error messages

oval_graph/_xml_parser_test_info.py, tests/test_data/JsTree_json0.json
This PR resolves references of variable  in OVAL details about test.
=> Resolve variable references

tests/any_test_help.py, tests/test_command_arf_to_graph.py, tests/test_command_arf_to_json.py, tests/test_command_json_to_graph.py
This PR creates command tests. These tests test the use of commands and the compatibility between the `arf-to-json` and `json-to-graph` commands.
=> Integration tests

oval_graph/client.py, oval_graph/json_to_html.py, tests/test_command_arf_to_graph.py, tests/test_command_arf_to_json.py
This PR fixes problem with combination of parameters ```--all``` and ```--show-filed-rules```. 
More info about problem is in #116. 
Fixes: #116
=> Fixes #116

oval_graph/_builder_html_graph.py, oval_graph/arf_to_html.py, oval_graph/arf_to_json.py, oval_graph/client.py, oval_graph/json_to_html.py, tests/any_test_help.py, tests/test_arf_to_json.py
This PR reworks classes which process commands. Because these classes were confusing. 
* Creates a class for creating HTML
* Creates a date as a constant
Fixes #128
=> Rework CLI classes

oval_graph/client.py, tests/any_test_help.py, tests/test_client.py
This PR improves message when inquirer is not installed.
Fixes #133
=> Improves message when inquirer is not installed

oval_graph/arf_to_html.py, oval_graph/client.py, oval_graph/json_to_html.py
This PR creates a shorter option for command arguments.
=> Creates a shorter option for command arguments

oval_graph/client.py
This PR creates an --version argument.
=> Creates an --version argument

.packit.yaml, build.sh, tag_version.sh
This PR includes:
* fixes a script build issue
* runs test before build
* prepares the build environment
* rework build script
* change PackIt relase config (Because when you create a release, PackIt creates too many unused PR into the RPM upstream.)
=> Build script

README.md, docs/GUIDE.md
This PR changes titles and the introductory sentence because the project name has changed.
=> Update project name in README and GUIDE

oval_graph/command_line.py, tests/test_command_arf_to_graph.py, tests/test_command_arf_to_json.py, tests/test_command_json_to_graph.py, tests/test_xml_parser.py
This PR implements print traceback with the verbose parameter. For better-debugging experience.
=> Print traceback with verbose

benchmark.py, benchmark_full_command.py, oval_graph/_builder_html_graph.py, oval_graph/arf_to_html.py, oval_graph/arf_to_json.py, oval_graph/client.py, oval_graph/json_to_html.py, tests/test_arf_to_json.py
This PR improves the HTML creation process. Reduces reads from the hard disk and speeds up the saving of generated HTMLs.
Edit: You can test improvement with benchmark script named  `benchmark_full_command.py`.
=> Improves performance when creating HTML

oval_graph/_builder_html_graph.py, oval_graph/arf_to_html.py, oval_graph/json_to_html.py, oval_graph/parts/css.txt, oval_graph/parts/script.js
This PR embeds search bar to HTML with graphs, when there are two or more graphs in one file.
(When is used parameter ``--all-in-one``)
Fixes #121
=> Embed search bar

oval_graph/command_line.py
This PR removes the use of  ```sys.argv``` in the project. 
Fixes #154
=> Removes the use of sys.argv in the project

oval_graph/client.py, tests/test_arf_to_hml.py, tests/test_command_arf_to_graph.py, tests/test_command_json_to_graph.py, tests/test_json_to_html.py
This PR removes the automatic opening of the web browser in the ```pytest```.
=> Automatically closes the web browser in tests

.flake8, .gitignore, README.md, docs/GUIDE.md, test_suite_requirements.txt, tests/test_command_arf_to_graph.py, tests/test_command_arf_to_json.py, tests/test_command_json_to_graph.py, tox.ini
-  creates config for the tox test suite
-  adds documentation about how to execute the test suite
-  adds tests for the syntax of code 
Fixes #158
=> Enhances test suite

oval_graph/_xml_parser_comments.py
=> Fix loading of ARF results when comment node is missing.

oval_graph/client.py, oval_graph/command_line.py
This PR fixes a problem with running commands. 
Fixes #166
[Here is fixed rpm for testing.](https://github.com/Honny1/rpm-oval-graph/tree/master/f32-fix)
=> Fixes an issue with entry points

README.md, docs/GUIDE.md
This PR fix links to the guide from the readme.
=> Fixes links to the guide

benchmark.py, benchmark_full_command.py, oval_graph/_builder_html_graph.py, oval_graph/converter.py, oval_graph/oval_node.py, oval_graph/xml_parser.py, setup.py, tests/any_test_help.py, tests/conftest.py, tests/data_cleaner.py, tests/test_command_arf_to_graph.py, tests/test_command_arf_to_json.py, tests/test_command_json_to_graph.py, tests/test_evaluate.py, tests/test_graph.py, tests/test_xml_parser.py, tox.ini
This PR fixes import sorting and removes unused imports.
=> Fix imports

.packit.yaml
Builds and installations passed for me: https://github.com/TomasTomecek/oval-graph/pull/1
Sorry about the breakage.
=> Fix builds with packit and re-add installation tests

.scrutinizer.yml
This PR creates scrutinizer-ci config for better managing CI config.
=> Create scrutinizer-ci config

build.sh, tag_version.sh
This PR changes the version tag prefix and improves build scripts.
=> Improves build scripts

oval_graph/parts/script.js
=> Fix CWE-628

.pylintrc, oval_graph/__init__.py, oval_graph/_builder_oval_tree.py, oval_graph/command_line.py, oval_graph/converter.py, oval_graph/evaluate.py, oval_graph/oval_node.py, oval_graph/xml_parser.py
- Documentation strings about the contents of the file where I think is helpful.
- Disables warning missing docstring about contents of the file in pylint config.  
- Renames Class BuilderOvalGraph to BuilderOvalTree.
=> Code documentation

.packit.yaml
This PR fixes the release problem with packit.
Fixes #193
=> Tag template to packit config

.gitignore, test_commands.sh
This PR changes the output of `test_commands.sh` according to #190.
Fixes #190
=> The output of test_commands.sh

oval_graph/oval_tree/oval_node.py, tests_oval_graph/test_oval_tree/test_oval_node.py
This PR fixes search in the OVAL tree.
Fixes #201
=> Fixes search in the OVAL tree

MANIFEST.in, docs/GUIDE.md, test_suite_requirements_no_inquirer.txt, tests_oval_graph/test_commands/test_command_arf_to_graph.py, tests_oval_graph/test_commands/test_command_arf_to_json.py, tests_oval_graph/test_commands/test_command_json_to_graph.py, tests_oval_graph/test_commands/test_command_line_client/test_client.py, tests_oval_graph/test_commands/test_command_line_client/test_client_arf_to_html.py, tests_oval_graph/test_commands/test_command_line_client/test_client_arf_to_json.py, tests_oval_graph/test_commands/test_command_line_client/test_client_json_to_html.py, tests_oval_graph/test_commands/test_command_line_client/test_clients_without_inquirer.py, tests_oval_graph/test_oval_evaluate/test_oval_evaluate.py, tox.ini
This PR contains a new part of the test suite for testing when the inquirer is not installed also fixes the imports.
=> New part of the test suite for testing when the inquirer is not installed

MANIFEST.in, docs/GUIDE.md, oval_graph/command_line_client/client.py, setup.py, test_suite_requirements.txt, tests_oval_graph/test_commands/test_command_arf_to_graph.py, tests_oval_graph/test_commands/test_command_arf_to_json.py, tests_oval_graph/test_commands/test_command_json_to_graph.py, tests_oval_graph/test_commands/test_command_line_client/test_client.py, tests_oval_graph/test_commands/test_command_line_client/test_client_arf_to_html.py, tests_oval_graph/test_commands/test_command_line_client/test_client_arf_to_json.py, tests_oval_graph/test_commands/test_command_line_client/test_client_json_to_html.py, tests_oval_graph/test_commands/test_command_line_client/test_clients_without_inquirer.py, tox.ini
This PR removes inquirer support
=> Remove inquirer support

oval_graph/arf_xml_parser/_comments.py, oval_graph/arf_xml_parser/_oval_scan_definitions.py, oval_graph/arf_xml_parser/_test_info.py, oval_graph/arf_xml_parser/arf_xml_parser.py, oval_graph/command_line.py, oval_graph/command_line_client/arf_to_json.py, oval_graph/command_line_client/client_arf_input.py, oval_graph/command_line_client/client_html_output.py, oval_graph/command_line_client/client_json_input.py, oval_graph/html_builder/graph.py, oval_graph/oval_tree/converter.py, oval_graph/parts/script.js, setup.py, test_commands.sh, tests_oval_graph/test_commands/test_command_arf_to_graph.py, tests_oval_graph/test_commands/test_command_arf_to_json.py, tests_oval_graph/test_commands/test_command_json_to_graph.py, tests_oval_graph/test_commands/test_command_line_client/test_client_arf_to_json.py, tests_oval_graph/test_oval_evaluate/test_oval_evaluate.py, tests_oval_graph/test_oval_tree/get_tree.py, tests_oval_graph/test_tools.py
This PR fixes details in code style.
- typos 
- pylitnt problems 
- js code style
=> Fix details
