graph/client.py
tests/test_client.py

- Optional arguments witch changing the choice of rules:
- `--showFailRules` - Show only FAIL rules
- `--showNotSelectedRules` - Show not selected rules, but you can't visualized this rules.
- Optional arguments witch changing behavior of tool:
- `--offWebBrowser` - It does not start the web browser.
-  `--removePassTests` - If graph have many nodes in graph, you can remove passing tests for better orientation. (Not implemented)

Append new optional arguments to client

---

oval_graph/client.py
tests/test_client.py

This PR changes PyInquirer library to inquirer. Because PyInquirer has problems with installation.

Changed PyInquirer library to inquirer

---

oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/command_line.py
setup.py
tests/any_test_help.py
tests/test_arf_to_json.py
tests/test_data/referenc_result_data_json.json

This PR include new command `arf-to-json` which transform rule form arf to json.
Fixes: #39 
Restore to graph command will be append in next PR.

Add command arf-to-json

---

oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/json_to_html.py
tests/any_test_help.py
tests/test_arf_to_json.py

This PR change function of parameter ```--out``` in command ```arf-to-json```.  User can store rules in one json file. 
Fixes: #67

Output to single JSON file

---

oval_graph/arf_to_html.py
oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/json_to_html.py
tests/any_test_help.py
tests/test_arf_to_hml.py
tests/test_arf_to_json.py
tests/test_client.py
tests/test_data/bad_result_data_json.json
tests/test_json_to_html.py

These PR contains:
- A new parameter `rule_name` in command `json-to-graph`. That can be used to search a rule stored in a json file.
- rework the json-to-graph class
- rework arg parser in Client class

New parameter in json-to-graph

---

oval_graph/arf_to_html.py
oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/exceptions.py
oval_graph/json_to_html.py
oval_graph/xml_parser.py
tests/test_xml_parser.py

This PR fixes a problem with unchecked rules (test file: ```tests/test_data/arf-scan-with-notchecked-rule.xml``` Rule:```xccdf_org.ssgproject.content_rule_security_patches_up_to_date```). The problem was caused by processing all rules. There was an interrupt while processing an unchecked rule. The same problem occurred when trying to process only an unchecked rule.

Fix notchecked rules

---

oval_graph/_xml_parser_oval_scan_definitions.py
oval_graph/converter.py
tests/test_JsTree_data/JsTree_data_negated_0.json
tests/test_JsTree_data/JsTree_data_negated_1.json
tests/test_JsTree_data/JsTree_data_negated_2.json
tests/test_JsTree_data/JsTree_data_negated_3.json

This PR fixes a problem with parsing negation. The problem is caused by saving the results of the negated test in ARF. Result of  negated test is negated whitch mean result of test has processed negation. When evaluating a tree, negation is processed. This results in double negation.

Fix processing negation

---

.packit.yaml
oval-graph.spec

- fix for missing important dependency `python3-lxml` for rpm. Sometimes finding dependencies does not install important dependencies for the application.
- update packit config to test all supported OSs (in details of install test you could see installed dependency `python3-lxml`, which was missed before)

Fixes requires

---

oval-graph.spec

This PR explicitly appends to spec file ```python3-setuptools``` because setuptools devs asked me to do it. Because it will helps with develop setuptools.

Uses explicitly build require python3-setuptools

---

oval_graph/arf_to_html.py
oval_graph/client.py
oval_graph/json_to_html.py

This PR implements option `--all-in-one` to json-to-graph command. User can generate HTML file with all graphs. This PR changes the name of the files generated by the `json-to-graph` command. Removes the date of the HTML file was generated and leaves the date the JSON was created.
Fixes #123 #118

Option --all-in-one in command json-to-graph

---

.packit.yaml

PackIt tests are disabled, because there is a problem with cloning of repository (git clone end with error code 128)

Disables PackIt tests

---

oval_graph/_builder_html_graph.py
oval_graph/arf_to_html.py
oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/command_line.py
oval_graph/json_to_html.py
tests/any_test_help.py
tests/test_arf_to_hml.py
tests/test_command_arf_to_graph.py
tests/test_command_json_to_graph.py
tests/test_json_to_html.py

This PR applies the rule of silence.
* renames --off-web-browser to --display
* reworks enabling and disabling the web browser
* changes default output directory to ```/tmp```
Fixes #132

Silent mode

---

oval_graph/arf_to_html.py
oval_graph/arf_to_json.py
oval_graph/client.py
oval_graph/json_to_html.py

This PR fixes duplicated definitions of command-line parsers.
Fixes #145

Fix duplicated definitions of command-line parsers

---

oval_graph/_builder_html_graph.py
oval_graph/client.py

This PR moves function for opening the web browser to the client because opening HTML will be used for future command `arf-to-report`.

Moves the open web browser to the client

---

README.md

This PR fixes README links and links on the PyPI page, but on [PyPI](https://pypi.org/project/oval-graph/) will not take effect until the next release (1.2.3).

Fixes links in  README

---

.pylintrc

This PR creates a pylint configuration.  The configuration puts the `` lxml`` library in the list of libraries that are not checked for E1101 because they contain C extensions.

Creates pylint config

---

.packit.yaml

This PR contains PackIt config improvements:
- Update URL upstream 
- Rename dist_git_branch to dist_git_branches, because it has been renamed in Packit. [Changelog](https://github.com/packit/packit/blob/main/CHANGELOG.md#0101)
- Add job for syncing spec file

PackIT config

---

MANIFEST.in

Test code, support scripts and data was not packaged along, so people who downloaded the pypi source package (that is also used as a Fedora source) can run the whole test suite without having to check out those files from Git.

Make sure that users can run tests from the sdist.

---

oval_graph/command_line.py
oval_graph/command_line_client/arf_to_json.py
oval_graph/command_line_client/client.py
oval_graph/command_line_client/client_arf_input.py
oval_graph/command_line_client/client_html_output.py
oval_graph/command_line_client/client_json_input.py
oval_graph/command_line_client/json_to_html.py
tests/any_test_help.py
tests/test_command_line_client/test_arf_to_hml.py
tests/test_command_line_client/test_arf_to_json.py
tests/test_command_line_client/test_json_to_html.py

* Reworks error handling related to rules that are not visualizable.
* Improves catching of errors in CLI.
* Fix bug with detection of parameter ```--verbose```.
* Removes loading files form ```__init__```.
* Changes the print format of not selected rules.
* New parameter ```--show-not-tested-rules``` for displaying rules which you can not visualizable. Rules with result `notappl`, `noteval`, etc.
* Imports inquirer on the top level.
* Creates getters for keys, rules ids and file names.

CLI improvement

---

oval_graph/command_line.py
oval_graph/command_line_client/client.py
oval_graph/command_line_client/client_html_output.py
oval_graph/html_builder/graph.py
tests_oval_graph/test_commands/command_constants.py
tests_oval_graph/test_commands/test_command_arf_to_graph.py
tests_oval_graph/test_commands/test_command_arf_to_json.py
tests_oval_graph/test_commands/test_command_json_to_graph.py
tests_oval_graph/test_tools.py

This PR fixes problem with saving the report to dir or to file when is used `--output`. When the user wants to generate more reports it will create OUTPUT as a directory.

Fix problem with saving the report to dir or to file when is used `--output`

---

oval_graph/arf_xml_parser/_test_info.py
tests_oval_graph/global_test_data/arf_no_system_data.xml
tests_oval_graph/test_arf_xml_parser/test_arf_xml_parser.py

This PR fixes issue with missing system data in the arf report and creates basic tests for this issue.
Fixes #204

Fix issue with missing system data in the arf report
